<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <PackagesDirectory>$(MSBuildThisFileDirectory)packages\</PackagesDirectory>
        <LocalWheelDirectory>$(MSBuildThisFileDirectory)wheels\</LocalWheelDirectory>
        <RestorePackagesPath>$(PackagesDirectory)</RestorePackagesPath>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <PyWinRTVersion>3.2.1</PyWinRTVersion>
        <PyWinRTPath>$(PackagesDirectory)pywinrt\$(PyWinRTVersion)\tools\$(TargetFramework)\any\PyWinRT.dll</PyWinRTPath>
        <PyWinRTExe>dotnet $(PyWinRTPath)</PyWinRTExe>
        <ScriptsDirectory>$(MSBuildThisFileDirectory)scripts\</ScriptsDirectory>
        <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
        <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    </PropertyGroup>

    <!-- Common output paths for PyWinRT package generation -->
    <PropertyGroup>
        <ObjPath Condition="'$(ObjPath)' == ''">$(MSBuildProjectDirectory)\obj</ObjPath>
        <PythonPackagePath Condition="'$(PythonPackagePath)' == ''">$(ObjPath)\pkg</PythonPackagePath>
        <PyWinRTOutputPath Condition="'$(PyWinRTOutputPath)' == ''">$(ObjPath)\gen</PyWinRTOutputPath>
        <PyWinRTHeaderPath Condition="'$(PyWinRTHeaderPath)' == ''">$(PythonPackagePath)\include\pywinrt</PyWinRTHeaderPath>
        <CppWinRTOutputPath Condition="'$(CppWinRTOutputPath)' == ''">$(PythonPackagePath)\include\cppwinrt</CppWinRTOutputPath>
    </PropertyGroup>
</Project>
