<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <PackagesDirectory>$(MSBuildThisFileDirectory)packages\</PackagesDirectory>
        <LocalWheelDirectory>$(MSBuildThisFileDirectory)wheels\</LocalWheelDirectory>
        <RestorePackagesPath>$(PackagesDirectory)</RestorePackagesPath>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <PyWinRTVersion>3.2.1</PyWinRTVersion>
        <PyWinRTPath>$(PackagesDirectory)pywinrt\$(PyWinRTVersion)\tools\$(TargetFramework)\any\PyWinRT.dll</PyWinRTPath>
        <PyWinRTExe>dotnet $(PyWinRTPath)</PyWinRTExe>
        <ScriptsDirectory>$(MSBuildThisFileDirectory)scripts\</ScriptsDirectory>
        <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
        <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
        <PythonVersion>3.12</PythonVersion>
    </PropertyGroup>

    <!-- Common output paths for PyWinRT package generation -->
    <PropertyGroup>
        <ObjPath>$(MSBuildProjectDirectory)\obj</ObjPath>
        <PythonPackagePath>$(ObjPath)\pkg</PythonPackagePath>
        <PyWinRTOutputPath>$(ObjPath)\gen</PyWinRTOutputPath>
        <PyWinRTHeaderPath>$(PythonPackagePath)\include\pywinrt</PyWinRTHeaderPath>
        <CppWinRTOutputPath>$(PythonPackagePath)\include\cppwinrt</CppWinRTOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <WinMDFolder Include="metadata" />
        <WinMDFolder Include="metadata\10.0.18362.0" />
    </ItemGroup>

    <!-- Common static package files for all component packages -->
    <ItemGroup>
        <PythonPackageFile Include="$(MSBuildProjectDirectory)\pyproject.toml" Condition="Exists('$(MSBuildProjectDirectory)\pyproject.toml')" />
        <PythonPackageFile Include="$(MSBuildProjectDirectory)\README.md" Condition="Exists('$(MSBuildProjectDirectory)\README.md')" />
    </ItemGroup>
</Project>
