name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"

    - name: Build Build Tasks
      run: dotnet build PyWinAppSDK.Build.Tasks/PyWinAppSDK.Build.Tasks.csproj -c Release

    - name: Run Rebuild and Test Script
      shell: pwsh
      run: .\rebuild_and_test.ps1

    - name: Upload Wheels
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: wheels
        path: wheels/*.whl
        retention-days: 5

    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: localpackages
        path: localpackages/*.nupkg
        retention-days: 5
